<a href="https://colab.research.google.com/github/patel-mahek/Arya/blob/Data-Science/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import numpy as np

### **Arrays**

In [ ]:
np.array([1,2,3,4])
a = np.array([1,2,3,4])
b = np.array([0,0.5,1,1.5,2])

In [ ]:
a[0],a[1]
a[1:3]
b[[0,2,-1]]

array([0., 1., 2.])

In [ ]:

np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [ ]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}, sys])
d.dtype

dtype('O')

In [ ]:
# multi dimensionalarrays

# 2-D
M = np.array([
    [1,2,3],
    [4,5,6]
])
M.shape

(2, 3)

In [ ]:
M.ndim

2

In [ ]:
M.size

6

In [ ]:
N = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],[
      [6,9,3],
      [4,0,2]
    ]
])

In [ ]:
N

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  9,  3],
        [ 4,  0,  2]]])

In [ ]:
N.shape

(2, 2, 3)

In [ ]:
N.ndim

3

In [ ]:
N.size

12

In [ ]:
# we cant create inconsistent shapes
# eg:

# C = np.array([
#     [
#         [12,5,9],
#         [2,8,12]
#     ],
#     [
#         [3,5,7]
#     ]
# ])



In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]


4

In [ ]:
A[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:

A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [ ]:
# broadcasting and vectorized operations
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a+10

array([10, 11, 12, 13])

In [ ]:
a*10

array([ 0, 10, 20, 30])

In [ ]:
a +=100
# alredy executed thrice

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [ ]:
a + b
# we need the arrys in shape for this

array([110, 111, 112, 113])

In [ ]:
a*b

array([1000, 1010, 1020, 1030])

In [ ]:
# Boolean arrays
a = np.arange(4)
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a >= 2


array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a[(a == 1) | (a == 3)]

array([1, 3])

In [ ]:
A = np.random.randint(50, size=(3, 3))

In [ ]:
A

array([[27,  8, 29],
       [17, 42, 16],
       [35, 11, 41]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([27, 29, 42, 35, 41])

In [ ]:
A[A>20]

array([27, 29, 42, 35, 41])

In [ ]:
# LINEAR ALGEBRA
A = np.random.randint(50,size=(3,3))
A

array([[15, 46,  0],
       [38, 25, 14],
       [30, 32, 46]])

In [ ]:
B = np.random.randint(50,size=(3,3))
B

array([[ 7, 26, 47],
       [13,  4, 19],
       [18, 18, 17]])

In [ ]:
A.dot(B)

array([[ 703,  574, 1579],
       [ 843, 1340, 2499],
       [1454, 1736, 2800]])

In [ ]:
A @ B

array([[ 703,  574, 1579],
       [ 843, 1340, 2499],
       [1454, 1736, 2800]])

In [ ]:
B.T

array([[ 7, 13, 18],
       [26,  4, 18],
       [47, 19, 17]])

In [ ]:
# Size of objects in Memory
sys.getsizeof(1)

28

In [ ]:
np.dtype(int).itemsize

8

In [ ]:
sys.getsizeof([1])


64

In [ ]:
np.array([1]).nbytes

8

In [ ]:
# Useful functions
# random
np.random.random(size=2)

array([0.91532263, 0.2402993 ])

In [ ]:
# arange
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
# reshape
np.arange(10).reshape(5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# linspace
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# zeros / ones / empty
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((3, 3), dtype=np.int_)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((2, 2))

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
# identity and eye
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(8, 7)


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'